{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- | Arrays as the monoidal array category @[C; I]@ of Abbott & Zardini.
--
-- = Overview
--
-- Abbott & Zardini define an array category @[C; I]@ from any base symmetric
-- monoidal category @C@ and any indexing category @I@.  Objects are synthetic
-- arrays @[X; P]@; morphisms are generated by two families:
--
-- * __Batch lift__ @[f; P]@ — apply a base morphism @f : X -> Y@ at every
--   index of shape @P@.
-- * __Reindexing__ @[X; η]@ — precompose with an indexing morphism
--   @η : P -> Q@.
--
-- This module gives a direct presheaf semantics: an array of shape @s@ over
-- base category @arr@ is a morphism @Fins s -> X@ in @arr@.  The two
-- generators are therefore exactly categorical composition in @arr@.
--
-- = Instantiations
--
-- * @arr = (->)@: arrays are functions from indices to values.
-- * @arr = Mat r@: arrays are functional matrices between finite index sets.
--
-- The module also provides a conceptual renaming: @backpermute@ in harpie
-- is 'reindex' in @[C; I]@.
module Circuit.Mat.Array
  ( -- * Indexing category
    IxMap,

    -- * Array category carrier
    ArrayC (..),

    -- * Base-category support
    LiftFun (..),
    Tabular (..),

    -- * Array-category operations
    reindex,
    batch,
    tabulateC,
    indexC,

    -- * Finite support for shape indices
    allFins,
  )
where

import Circuit.Category (Category (..))
import Circuit.Mat (Finite (..), Mat (..), runMat)
import Data.Bool (bool)
import Data.Kind (Constraint, Type)
import GHC.TypeNats (Nat)
import Harpie.Shape (Fins (..), KnownNats (..), valuesOf)
import NumHask.Algebra.Additive (Additive (..))
import NumHask.Algebra.Multiplicative (Multiplicative (..))
import Prelude hiding (id, (.))

-- $setup
--
-- >>> :set -XDataKinds
-- >>> :set -XTypeApplications
-- >>> import Harpie.Shape
-- >>> import Circuit.Mat.Array

-- | A morphism in the indexing category @I@: a map between shape indices.
type IxMap (s' :: [Nat]) (s :: [Nat]) = Fins s' -> Fins s

-- | Arrays in the array category @[C; I]@.
--
-- An array of shape @s@ with values in object @a@ is a morphism
-- @Fins s -> a@ in the base category @arr@.
newtype ArrayC (arr :: Type -> Type -> Type) (s :: [Nat]) (a :: Type) = ArrayC
  { runArrayC :: arr (Fins s) a
  }

-- | Lift a plain function to a morphism in the base category.
--
-- For functions this is the identity; for matrices it is the 'Fun'
-- constructor.
class (Category arr) => LiftFun arr where
  liftFun :: (i -> j) -> arr i j

instance LiftFun (->) where
  liftFun = id

instance LiftFun (Mat r) where
  liftFun = Fun

-- | Categories that can represent a functional relation @i -> j@ as a
-- morphism and recover it.
--
-- The @Mat r@ instance builds a matrix with a single 'one' in each row
-- and recovers the function by looking for that 'one'.  It therefore
-- requires the matrix to be functional.
class (Category arr) => Tabular arr where
  type TabulateOb arr (i :: Type) (j :: Type) :: Constraint

  tabulateArr :: (TabulateOb arr i j) => (i -> j) -> arr i j
  indexArr :: (TabulateOb arr i j) => arr i j -> (i -> j)

instance Tabular (->) where
  type TabulateOb (->) i j = ()
  tabulateArr = id
  indexArr = id

instance Tabular (Mat r) where
  type TabulateOb (Mat r) i j = (Finite i, Finite j, Eq j, Additive r, Multiplicative r, Eq r)
  tabulateArr f = Mat (\i j -> bool zero one (f i == j))
  indexArr m i =
    case filter (\j -> runMat m i j == one) universe of
      [j] -> j
      [] -> error "Circuit.Mat.Array.indexArr: no value at index"
      _ -> error "Circuit.Mat.Array.indexArr: non-functional matrix at index"

-- | Reindexing morphism @[X; η]@.
--
-- Precompose with an indexing morphism.  This is exactly harpie's
-- @backpermute@, renamed to match the paper.
reindex ::
  (LiftFun arr) =>
  IxMap s' s ->
  ArrayC arr s a ->
  ArrayC arr s' a
reindex eta (ArrayC m) = ArrayC (m . liftFun eta)

-- | Batch lift @[f; P]@.
--
-- Apply a base morphism at every index of the array.
batch ::
  (Category arr) =>
  arr a b ->
  ArrayC arr s a ->
  ArrayC arr s b
batch f (ArrayC m) = ArrayC (f . m)

-- | Separator / tabulation: build an array from a function on indices.
--
-- This is the separator @Sp@ of the paper, mapping the presheaf
-- representation back to an array object.
tabulateC ::
  (Tabular arr, TabulateOb arr (Fins s) a) =>
  (Fins s -> a) ->
  ArrayC arr s a
tabulateC f = ArrayC (tabulateArr f)

-- | Join / lookup: recover the function on indices from an array.
--
-- This is the join @Jn@ of the paper.
indexC ::
  (Tabular arr, TabulateOb arr (Fins s) a) =>
  ArrayC arr s a ->
  (Fins s -> a)
indexC (ArrayC m) = indexArr m

-- | All indices of a statically-known shape.
allFins :: forall s. (KnownNats s) => [Fins s]
allFins = UnsafeFins <$> enumerateShape (valuesOf @s)
  where
    enumerateShape [] = [[]]
    enumerateShape (n : ns) = [i : rest | i <- [0 .. n - 1], rest <- enumerateShape ns]

instance (KnownNats s) => Finite (Fins s) where
  universe = allFins @s

instance Functor (ArrayC (->) s) where
  fmap f (ArrayC g) = ArrayC (f . g)

instance Applicative (ArrayC (->) s) where
  pure a = ArrayC (const a)
  ArrayC f <*> ArrayC x = ArrayC (\i -> f i (x i))
